If you've ever used NumPy, tensors are kind of like NumPy arrays (we'll see more on this later).

For the sake of this notebook and going forward, you can think of a tensor as a multi-dimensional numerical representation (also referred to as n-dimensional, where n can be any number) of something. Where something can be almost anything you can imagine:

- It could be numbers themselves (using tensors to represent the price of houses).
- It could be an image (using tensors to represent the pixels of an image).
- It could be text (using tensors to represent words).
- Or it could be some other form of information (or data) you want to represent with numbers.

The main difference between tensors and NumPy arrays (also an n-dimensional array of numbers) is that tensors can be used on GPUs (graphical processing units) and TPUs (tensor processing units).

The benefit of being able to run on GPUs and TPUs is faster computation, this means, if we wanted to find patterns in the numerical representations of our data, we can generally find them faster using GPUs and TPUs.

Okay, we've been talking enough about tensors, let's see them.

The first thing we'll do is import TensorFlow under the common alias tf.

In [2]:
# Import TensorFlow

import tensorflow as tf
print(tf.__version__)

2.15.0


In [12]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [15]:
# Tensorflow has inbuilt functions such as tf.io or tf.data to read data and convert them to tensors

# Create a scalar
scalar = tf.constant(7)
scalar

# ndim is number of dimensions
scalar.ndim
 
# A scalar is a rank 0 tensor, (it has no dimension). 
# A tensor can have unlimited range of dimension depending on the input data representation

<tf.Tensor: shape=(), dtype=int32, numpy=7>

0

In [16]:
# Create a vector with more than 1 dimension
# Check the ndim of vector
vector = tf.constant([10, 10])
vector
vector.ndim

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

1

In [18]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                     [2, 3]])
matrix
matrix.ndim

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  3]], dtype=int32)>

2

 By default TF creates tensor of either int32 or float32 datatype. Higher the number more the precise the number and more space it takes on the computer

In [20]:
# create another matrix and define datatype
another_matrix = tf.constant(
    [
        [10., 7.],
        [2., 3.]
    ], dtype=tf.float16
)
another_matrix
another_matrix.ndim

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 2.,  3.]], dtype=float16)>

2

In [22]:
tensor = tf.constant([
    [[1, 2, 3],
     [4, 5, 6]],
    [[7, 8, 9],
     [10, 11, 12]],
    [[13, 14, 25],
     [16, 17, 18]]]
)
tensor
tensor.ndim

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 25],
        [16, 17, 18]]], dtype=int32)>

3

In [23]:
another_tensor = tf.constant([
    [[], []], # 1 Dim
    [[], []], # 2 Dim
    [[], []]  # 3 Dim
])
another_tensor.ndim

3